apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pcidevices.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: PCIDevice
    plural: pcidevices
    singular: pcidevice
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.address
      name: Address
      type: string
    - jsonPath: .status.vendorId
      name: Vendor Id
      type: string
    - jsonPath: .status.deviceId
      name: Device Id
      type: string
    - jsonPath: .status.nodeName
      name: Node Name
      type: string
    - jsonPath: .status.description
      name: Description
      type: string
    - jsonPath: .status.kernelDriverInUse
      name: Kernel Driver In Use
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
          status:
            properties:
              address:
                nullable: true
                type: string
              classId:
                nullable: true
                type: string
              description:
                nullable: true
                type: string
              deviceId:
                nullable: true
                type: string
              iommuGroup:
                nullable: true
                type: string
              kernelDriverInUse:
                nullable: true
                type: string
              nodeName:
                nullable: true
                type: string
              resourceName:
                nullable: true
                type: string
              vendorId:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pcideviceclaims.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: PCIDeviceClaim
    plural: pcideviceclaims
    singular: pcideviceclaim
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.address
      name: Address
      type: string
    - jsonPath: .spec.nodeName
      name: Node Name
      type: string
    - jsonPath: .spec.userName
      name: User Name
      type: string
    - jsonPath: .status.kernelDriverToUnbind
      name: Kernel Driver Το Unbind
      type: string
    - jsonPath: .status.passthroughEnabled
      name: Passthrough Enabled
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                nullable: true
                type: string
              nodeName:
                nullable: true
                type: string
              userName:
                nullable: true
                type: string
            type: object
          status:
            properties:
              kernelDriverToUnbind:
                nullable: true
                type: string
              passthroughEnabled:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sriovnetworkdevices.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: SRIOVNetworkDevice
    plural: sriovnetworkdevices
    singular: sriovnetworkdevice
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.address
      name: Address
      type: string
    - jsonPath: .spec.nodeName
      name: Node Name
      type: string
    - jsonPath: .spec.numVFs
      name: NumVFs
      type: string
    - jsonPath: .status.vfAddresses
      name: VF Addresses
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                nullable: true
                type: string
              nodeName:
                nullable: true
                type: string
              numVFs:
                type: integer
            type: object
          status:
            properties:
              status:
                nullable: true
                type: string
              vfAddresses:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              vfPCIDevices:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodes.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: Node
    plural: nodes
    singular: node
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
        type: object
    served: true
    storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sriovgpudevices.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: SRIOVGPUDevice
    plural: sriovgpudevices
    singular: sriovgpudevice
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.address
      name: Address
      type: string
    - jsonPath: .spec.nodeName
      name: Node Name
      type: string
    - jsonPath: .spec.enabled
      name: Enabled
      type: string
    - jsonPath: .status.vGPUDevices
      name: VGPUDevices
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                nullable: true
                type: string
              enabled:
                type: boolean
              nodeName:
                nullable: true
                type: string
            type: object
          status:
            properties:
              vGPUDevices:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              vfAddresses:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vgpudevices.devices.harvesterhci.io
spec:
  group: devices.harvesterhci.io
  names:
    kind: VGPUDevice
    plural: vgpudevices
    singular: vgpudevice
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.address
      name: Address
      type: string
    - jsonPath: .spec.nodeName
      name: Node Name
      type: string
    - jsonPath: .spec.enabled
      name: Enabled
      type: string
    - jsonPath: .status.uuid
      name: UUID
      type: string
    - jsonPath: .status.configureVGPUTypeName
      name: VGPUType
      type: string
    - jsonPath: .spec.parentGPUDeviceAddress
      name: ParentGPUDevice
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                nullable: true
                type: string
              enabled:
                type: boolean
              nodeName:
                nullable: true
                type: string
              parentGPUDeviceAddress:
                nullable: true
                type: string
              vGPUTypeName:
                nullable: true
                type: string
            type: object
          status:
            properties:
              availableTypes:
                additionalProperties:
                  nullable: true
                  type: string
                nullable: true
                type: object
              configureVGPUTypeName:
                nullable: true
                type: string
              uuid:
                nullable: true
                type: string
              vGPUStatus:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vlanconfigs.network.harvesterhci.io
spec:
  conversion:
    strategy: None
  group: network.harvesterhci.io
  names:
    kind: VlanConfig
    listKind: VlanConfigList
    plural: vlanconfigs
    shortNames:
    - vc
    - vcs
    singular: vlanconfig
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.clusterNetwork
      name: CLUSTERNETWORK
      type: string
    - jsonPath: .spec.description
      name: DESCRIPTION
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterNetwork:
                type: string
              description:
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              uplink:
                properties:
                  bondOptions:
                    description: 'reference: https://www.kernel.org/doc/Documentation/networking/bonding.txt'
                    properties:
                      miimon:
                        default: -1
                        minimum: -1
                        type: integer
                      mode:
                        default: active-backup
                        enum:
                        - balance-rr
                        - active-backup
                        - balance-xor
                        - broadcast
                        - 802.3ad
                        - balance-tlb
                        - balance-alb
                        type: string
                    type: object
                  linkAttributes:
                    properties:
                      hardwareAddr:
                        description: A HardwareAddr represents a physical hardware
                          address.
                        format: byte
                        type: string
                      mtu:
                        minimum: 0
                        type: integer
                      txQLen:
                        default: -1
                        minimum: -1
                        type: integer
                    type: object
                  nics:
                    items:
                      type: string
                    type: array
                type: object
            required:
            - clusterNetwork
            - uplink
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}